### ISSUE TITLE
To-dos

### ISSUE THREAD

**Issue by graphemecluster** [Cantoboard/Cantoboard#42]
- [x] Swipe down rebound animation on key touch ended at `KeyView.swift` (#45)
- [x] `delete.left.fill` (#57)
- [x] `keyHighlightedShadowColor` (#57)
- [x] Option to use buffered input mode in Chinese but immediate input mode in English to match iOS default behavior (#63)
- [x] Option to determine half/full width according to Chinese/English input mode but not context before to match iOS default behavior (#64)
- [x] Center candidate view in iPad (#71)
- ~~Popup only the swipe down character while long-clicking in iPad~~
- ~~Option to limit English candidates to 3 in English mode~~
- ~~Different image assets for iPad~~

**Comment by alex-the-man** [comment]
>  Option to limit English candidates to 3 in English mode

Could the user just ignore the extra candidates?

**Comment by graphemecluster** [comment]
> Could the user just ignore the extra candidates? Add too many options might provide a worse UX

iOS does not provide any options at all, thus some options can be removed in fact.

Anyway, the main reasons I wrote this down are the appearance and the ease to click the correct candidate. Widening the margin between candidates in English input mode may be enough though.

**Comment by graphemecluster** [comment]
I also think of an option to auto-capitalize only in English input mode.

**Comment by alex-the-man** [comment]
> Anyway, the main reasons I wrote this down are the appearance and the ease to click the correct candidate. Widening the margin between candidates in English input mode may be enough though.

I'm open to tuning the font size. The app already has a larger font setting. May be the font isn't large enough.

**Comment by graphemecluster** [comment]
> I'm open to tuning the font size. The app already has a larger font setting. May be the font isn't large enough. We could also darken the candidate cell a bit to provide visual clue of the boundary of the candidate cells.

No, I mean, the candidate bar might be too tight between two English candidates for some people, not the size.

**Comment by graphemecluster** [comment]
Let me close the issue first. Subject to reopen.
